FROM python:3.8-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./db ./db
COPY ./main_pegas.py ./main_pegas.py

CMD [ "python3", "main_pegas.py" ]