apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: app
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: python
          image: '{{ .Values.werf.image.app }}'
          workingDir: /app
          env:
            - name: EKP_PLUGIN_ID
              value: {{ .Chart.Name }}
            - name: REDIS_HOST
              value: '{{ .Values.redis.host }}'
            - name: REDIS_PASSWORD
              value: '{{ .Values.redis.password }}'
            - name: REDIS_DB
              value: '{{ .Values.redis.db }}'
          ports:
            - containerPort: 3001
              protocol: TCP